In [1]:
import pandas as pd
import numpy as np

In [2]:
cereals = pd.read_csv(r"D:\Imarticus\PGDA_43\SQL\Datasets\1. Cereals Dataset with Questions\cereals_data.csv")

In [3]:
cereals

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,25,2,1.0,1.00,27.753301
74,Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,25,1,1.0,1.00,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,25,1,1.0,0.75,36.187559

In [4]:
cereals.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

### 1. Add index name fast on name

In [5]:
cereals.index.name = 'fast'

In [6]:
cereals.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
fast,,,,,,,,,,,,,,,,
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

### 2. Describe the schema of table

In [7]:
cereals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     76 non-null     float64
 9   sugars    76 non-null     float64
 10  potass    75 non-null     float64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     int64
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(7), int64(6), object(3)
memory usage: 9.8+ KB

### 3. Create view name as see where users can not see type column [first run appropriate query then create view]

In [8]:
see = cereals[['name','mfr','calories','protein','fat','sodium','fiber','carbo','sugars','potass','vitamins','shelf','weight','cups','rating']]

In [9]:
see.head()

,name,mfr,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
fast,,,,,,,,,,,,,,,
0,100%_Bran,N,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

### 4. Rename the view as saw

In [10]:
saw = see

In [11]:
saw.head()

,name,mfr,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
fast,,,,,,,,,,,,,,,
0,100%_Bran,N,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

### 5. Count how many are cold cereals

In [14]:
cereals.type.value_counts()[0:1].reset_index()

  type  count
0    C     74

### 6. Count how many cereals are kept in shelf 3

In [23]:
cereals.shelf.value_counts()[0:1].reset_index()

   shelf  count
0      3     36

### 7. Arrange the table from high to low according to ratings

In [28]:
cereals.sort_values(by= 'rating', ascending= False)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
fast,,,,,,,,,,,,,,,,
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.00,0.50,93.704912
64,Shredded_Wheat_'n'Bran,N,C,90,3,0,0,4.0,19.0,0.0,140.0,0,1,1.00,0.67,74.472949
65,Shredded_Wheat_spoon_size,N,C,90,3,0,0,3.0,20.0,0.0,120.0,0,1,1.00,0.67,72.801787
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.00,0.33,68.402973
63,Shredded_Wheat,N,C,80,2,0,0,3.0,16.0,0.0,95.0,0,1,0.83,1.00,68.235885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,Cocoa_Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446
18,Count_Chocula,G,C,110,1,1,180,0.0,12.0,13.0,65.0,25,2,1.00,1.00,22.396513
35,Honey_Graham_Ohs,Q,C,120,1,2,220,1.0,12.0,11.0,45.0,25,2,1.00,1.00,21.871292
12,Cinnamon_Toast_Crunch,G,C,120,1,3,210,0.0,13.0,9.0,45.0,25,2,1.00,0.75,19.823573
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12.0,35.0,25,2,1.00,0.75,18.042851

### 8. Suggest some column/s which can be Primary key

### 9. Find average of calories of hot cereal and cold cereal in one query

In [30]:
cereals.groupby(['type'])['calories'].mean().round(2).reset_index()

  type  calories
0    C    107.16
1    H    100.00

### 10. Add new column as HL_Calories where more than average calories should be categorized as HIGH and less than average calories should be categorized as LOW

In [31]:
output = []
for i in cereals.calories:
    if i > cereals.calories.mean():
        output.append('HIGH')
    else:
        output.append('LOW')

In [32]:
cereals.calories.mean()

106.88311688311688

In [33]:
cereals['HL_Calories'] = output

In [34]:
cereals.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,HL_Calories
fast,,,,,,,,,,,,,,,,,
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973,LOW
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679,HIGH
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505,LOW
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912,LOW
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843,HIGH

### 11. List only those cereals whose name begins with B

In [35]:
for i in cereals['name']:
    if i[0] == 'B':
        print(i)

Basic_4
Bran_Chex
Bran_Flakes

### 12. List only those cereals whose name begins with F

In [17]:
for  i in cereals['name']:
    if i[0] == 'F':
        print(i)

Froot_Loops
Frosted_Flakes
Frosted_Mini-Wheats
Fruit_&_Fibre_Dates,_Walnuts,_and_Oats
Fruitful_Bran
Fruity_Pebbles

### 13. List only those cereals whose name ends with s

In [18]:
for  i in cereals['name']:
    if i[-1] == 's':
        print(i)

Apple_Cinnamon_Cheerios
Apple_Jacks
Bran_Flakes
Cheerios
Clusters
Cocoa_Puffs
Corn_Flakes
Corn_Pops
Crispy_Wheat_&_Raisins
Froot_Loops
Frosted_Flakes
Frosted_Mini-Wheats
Fruit_&_Fibre_Dates,_Walnuts,_and_Oats
Fruity_Pebbles
Golden_Grahams
Grape_Nuts_Flakes
Grape-Nuts
Honey_Graham_Ohs
Honey_Nut_Cheerios
Just_Right_Crunchy__Nuggets
Lucky_Charms
Muesli_Raisins,_Dates,_&_Almonds
Muesli_Raisins,_Peaches,_&_Pecans
Multi-Grain_Cheerios
Quaker_Oat_Squares
Raisin_Squares
Rice_Krispies
Smacks
Strawberry_Fruit_Wheats
Total_Corn_Flakes
Triples
Wheaties

### 14. Select only those records which are HIGH in column HL_calories

In [19]:
cereals[cereals.HL_Calories == 'HIGH']

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,HL_Calories
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.00,1.00,33.983679,HIGH
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.00,0.75,34.384843,HIGH
5,Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,25,1,1.00,0.75,29.509541,HIGH
6,Apple_Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,25,2,1.00,1.00,33.174094,HIGH
7,Basic_4,G,C,130,3,2,210,2.0,18.0,8.0,100.0,25,3,1.33,0.75,37.038562,HIGH
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12.0,35.0,25,2,1.00,0.75,18.042851,HIGH
11,Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999,HIGH
12,Cinnamon_Toast_Crunch,G,C,120,1,3,210,0.0,13.0,9.0,45.0,25,2,1.00,0.75,19.823573,HIGH
13,Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208,HIGH
14,Cocoa_Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446,HIGH
15,Corn_Chex,R,C,110,2,0,280,0.0,22.0,3.0,25.0,25,1,1.00,1.00,41.445019,HIGH
17,Corn_Pops,K,C,110,1,0,90,1.0,13.0,12.0,20.0,25,2,1.00,1.00,35.782791,HIGH
18,Count_Chocula,G,C,110,1,1,180,0.0,12.0,13.0,65.0,25,2,1.00,1.00,22.396513,HIGH
19,Cracklin'_Oat_Bran,K,C,110,3,3,140,4.0,10.0,7.0,160.0,25,3,1.00,0.50,40.448772,HIGH
21,Crispix,K,C,110,2,0,220,1.0,21.0,3.0,30.0,25,3,1.00,1.00,46.895644,HIGH
24,Froot_Loops,K,C,110,2,1,125,1.0,11.0,13.0,30.0,25,2,1.00,1.00,32.207582,HIGH
25,Frosted_Flakes,K,C,110,1,0,200,1.0,14.0,11.0,25.0,25,1,1.00,0.75,31.435973,HIGH
27,"Fruit_&_Fibre_Dates,_Walnuts,_and_Oats",P,C,120,3,2,160,5.0,12.0,10.0,200.0,25,3,1.25,0.67,40.917047,HIGH
28,Fruitful_Bran,K,C,120,3,0,240,5.0,14.0,12.0,190.0,25,3,1.33,0.67,41.015492,HIGH
29,Fruity_Pebbles,P,C,110,1,1,135,0.0,13.0,12.0,25.0,25,2,1.00,0.75,28.025765,HIGH
31,Golden_Grahams,G,C,110,1,1,280,0.0,15.0,9.0,45.0,25,2,1.00,0.75,23.804043,HIGH
33,Grape-Nuts,P,C,110,3,0,170,3.0,17.0,3.0,90.0,25,3,1.00,0.25,53.371007,HIGH
34,Great_Grains_Pecan,P,C,120,3,3,75,3.0,13.0,4.0,100.0,25,3,1.00,0.33,45.811716,HIGH
35,Honey_Graham_Ohs,Q,C,120,1,2,220,1.0,12.0,11.0,45.0,25,2,1.00,1.00,21.871292,HIGH
36,Honey_Nut_Cheerios,G,C,110,3,1,250,1.5,11.5,10.0,90.0,25,1,1.00,0.75,31.072217,HIGH
37,Honey-comb,P,C,110,1,0,180,0.0,14.0,11.0,35.0,25,1,1.00,1.33,28.742414,HIGH
38,Just_Right_Crunchy__Nuggets,K,C,110,2,1,170,1.0,17.0,6.0,60.0,100,3,1.00,1.00,36.523683,HIGH
39,Just_Right_Fruit_&_Nut,K,C,140,3,1,170,2.0,20.0,9.0,95.0,100,3,1.30,0.75,36.471512,HIGH
40,Kix,G,C,110,2,1,260,0.0,21.0,3.0,40.0,25,2,1.00,1.50,39.241114,HIGH
42,Lucky_Charms,G,C,110,2,1,180,0.0,12.0,12.0,55.0,25,2,1.00,1.00,26.734515,HIGH
44,"Muesli_Raisins,_Dates,_&_Almonds",R,C,150,4,3,95,3.0,16.0,11.0,170.0,25,3,1.00,1.00,37.136863,HIGH
45,"Muesli_Raisins,_Peaches,_&_Pecans",R,C,150,4,3,150,3.0,16.0,11.0,170.0,25,3,1.00,1.00,34.139765,HIGH
46,Mueslix_Crispy_Blend,K,C,160,3,2,150,3.0,17.0,13.0,160.0,25,3,1.50,0.67,30.313351,HIGH
48,Nut&Honey_Crunch,K,C,120,2,1,190,0.0,15.0,9.0,40.0,25,2,1.00,0.67,29.924285,HIGH
49,Nutri-Grain_Almond-Raisin,K,C,140,3,2,220,3.0,21.0,7.0,130.0,25,3,1.33,0.67,40.692320,HIGH
51,Oatmeal_Raisin_Crisp,G,C,130,3,2,170,1.5,13.5,10.0,120.0,25,3,1.25,0.50,30.450843,HIGH
52,Post_Nat._Raisin_Bran,P,C,120,3,1,200,6.0,11.0,14.0,260.0,25,3,1.33,0.67,37.840594,HIGH
58,Raisin_Bran,K,C,120,3,1,210,5.0,14.0,12.0,240.0,25,2,1.33,0.75,39.259197,HIGH
61,Rice_Chex,R,C,110,1,0,240,0.0,23.0,2.0,30.0,25,1,1.00,1.13,41.998933,HIGH
62,Rice_Krispies,K,C,110,2,0,290,0.0,22.0,3.0,35.0,25,1,1.00,1.00,40.560159,HIGH
66,Smacks,K,C,110,2,1,70,1.0,9.0,15.0,40.0,25,2,1.00,0.75,31.230054,HIGH
67,Special_K,K,C,110,6,0,230,1.0,16.0,3.0,55.0,25,1,1.00,1.00,53.131324,HIGH
69,Total_Corn_Flakes,G,C,110,2,1,200,0.0,21.0,3.0,35.0,100,3,1.00,1.00,38.839746,HIGH
70,Total_Raisin_Bran,G,C,140,3,1,190,4.0,15.0,14.0,230.0,100,3,1.50,1.00,28.592785,HIGH
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.00,0.75,39.106174,HIGH
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,25,2,1.00,1.00,27.753301,HIGH
76,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,25,1,1.00,0.75,36.187559,HIGH

### 15. Find maximum of ratings

In [29]:
cereals['rating'].max()

93.704912

### 16. Find average ratings of those were High and Low calories

In [24]:
cereals.groupby('HL_Calories')['rating'].mean().round(2)

HL_Calories
HIGH    34.92
LOW     54.80
Name: rating, dtype: float64

### 17. Craete two examples of Sub Queries of your choice and give explanation in the script itself with remarks by using #

In [62]:
cereals[['mfr','rating']].groupby('mfr').max()

        rating
mfr
A    54.850917
G    51.592193
K    93.704912
N    74.472949
P    53.371007
Q    63.005645
R    49.787445

### 18. Remove column fat

In [16]:
cereals_updated = cereals.drop(columns= 'fat')

In [17]:
cereals_updated.head()

,name,mfr,type,calories,protein,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
fast,,,,,,,,,,,,,,,
0,100%_Bran,N,C,70,4,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,C,120,3,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,C,110,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843

### 19. Count records for each manufacturer mfr

In [21]:
cereals['mfr'].value_counts()

mfr
K    23
G    22
P     9
Q     8
R     8
N     6
A     1
Name: count, dtype: int64

### 20. Select name, calories and ratings only

In [22]:
cereals[['name','calories','rating']]

                         name  calories     rating
0                   100%_Bran        70  68.402973
1           100%_Natural_Bran       120  33.983679
2                    All-Bran        70  59.425505
3   All-Bran_with_Extra_Fiber        50  93.704912
4              Almond_Delight       110  34.384843
..                        ...       ...        ...
72                    Triples       110  39.106174
73                       Trix       110  27.753301
74                 Wheat_Chex       100  49.787445
75                   Wheaties       100  51.592193
76        Wheaties_Honey_Gold       110  36.187559

[77 rows x 3 columns]